---
params:
  apt : "EDDS"
  date: !r lubridate::today()
  df: !r mtcars
title: "`r params$apt`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

# Home {data-icon="fa-list"}


Cool text before anything starts!

```{r}
summary(params$df)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

***

This report was created on `r params$date` and presents the performance at `r params$apt`. 

Column {data-width=350}
-----------------------------------------------------------------------

### ValueBox Example


```{r}
spam <- runif(n=1, min = 0, max = 100)
spam <- round(spam, digits = 2)
valueBox(spam
         ,icon = "fa-trash"
         ,color = ifelse(spam > 50, "warning", "primary"))
```


### Gauge Example 

```{r}
rate <- runif(n=1, min = 0, max = 100)
rate <- round(rate, digits = 2)
gauge(rate, min = 0, max = 100, symbol = "%"
      ,gaugeSectors(success = c(80,100)
                    ,warning = c(40,79)
                    ,danger  = c(0,39)
                    )
      )
```

> Does this work for any commentary on the Value Boxes and Gauges? The text is pretty small (maybe increase with CSS).

### Chart C

```{r}
DT::datatable(
    mtcars
  , options = list(pageLength = 25)
  )
```

# More Stuff

This needs to be further developed

# Info & Disclaimer {data-icon="fa-question-circle"}

This page will comprise info and disclaimer