---
title: "Pan-European Performance Dashboard"
author: "PRU"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: paper
    #favicon: data-test/euctrl-logo-noname.png
    logo: data-test/euctrl-logo-noname-hgt48.png
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(leaflet)
library(DT)         # interactive tables
library(crosstalk)  # inter-widget interactivity
```

```{r}
apts <- read_csv("./data-test/airports.dat", col_names = FALSE) %>%
  rename(ICAO = X6, LAT = X7, LON = X8, TZ = X12) %>%
  select(ICAO, LAT, LON, TZ) %>%
  filter(ICAO %in% c("EGLL","EGKK","EDDF","EDDM","EIDW","EHAM","LSZH","LFPG","LEMD"))

#develop without crosstalk: ds <- apts
ds <- SharedData$new(apts)
```

# Home {data-icon="fa-list"}

Column 
-------------------------------------

### Overview

For more information contact <a href="mailto:pru@eurocontrol.int?subject=Airport Dashboard">PRU Support</a>.

### Filters

```{r filters}
filter_select(
  id = "ICAO",
  label = "myICAO",
  sharedData = ds,
  group = ~ICAO
)
```


### Cool Datatable

```{r}
DT::datatable(
  ds,
  filter = "top",
  extensions = "Scroller",
  rownames = FALSE,
  style = "bootstrap",
  class = "compact",
  width = "100%" #,
  #options = list(deferRender = TRUE, scrollY = 300, scroller = TRUE)
  )
```



Column
-----------------------------------------------------------------------

### Plot

this is were my cool stuff goes

```{r}
head(apts)
```

```{r}
mp <- leaflet() %>% 
  addTiles() %>% 
#  fitBounds(-127.44,24.05,-65.30,50.35) %>% 
  # addProviderTiles("Esri.WorldTopoMap") %>%
  #throws error with crosstalk: addCircleMarkers(
  addMarkers(apts$LON, 
                   apts$LAT, 
          #circle-marker         color = "red" #factor(apts$LON), 
          #circle-marker         ,radius = 6
          #circle-marker         , fill = TRUE
          #circle-marker         , fillOpacity = 0.2
          #circle-marker         , opacity = 0.6
                   , label = paste("<a href='", apts$ICAO,".html'>", apts$ICAO,"</a>", sep = "")
                  #, popup='<a href="https://www.r-project.org/">R Project</a>'
                  
                  ,clusterOptions = markerClusterOptions()
                   ) 
#%>%
#  addLegend("bottomleft", 
#            colors = c("orange","green", "red", "black"),
#            labels = c("Cleanup in progress.",
#                       "Cleanup complete.",
#                       "Status unclear.",
#                       "No potential for radioactive contamination."), 
#            opacity = 0.8)


mp
```

