---
title: "Data- and Formattable"
author: "RQ"
date: "15/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
library(formattable)
library(sparkline)
```

```{r}
YEAR <- c(2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,2020,2020)
MONTH<- c(3   ,4   ,5   ,6   ,7   ,8   ,9   ,10  ,11  ,12  ,1   ,2   )
ASMA <- c(3   ,3.2 ,3.4 ,3.3 ,4   ,4.2 ,3.8 ,3.2 ,2.9 ,2.5 ,2.8 ,3   )

ds <- tibble(YEAR = YEAR, MONTH_NUM = MONTH, ASMA=ASMA)
```

## Walk before you run - basics

```{r}
# default datatable
datatable(ds)

# cut down data table to pure table
# use options to defined DOM elements shown/used
datatable(ds, options = list(dom = 't'))

# constrain page length
datatable(ds, options = list(
   dom        = 't' # show only table
  ,pageLength = 5   # number of rows shown
))
```

## Do some calcs and present them

```{r}
tfc  <- readxl::read_excel("./data-test/Airport_Traffic.xlsx", sheet = "DATA")
asma <- readxl::read_excel("./data-test/ASMA_Additional_Time.xlsx", sheet = "DATA")
txot <- readxl::read_excel("./data-test/Taxi-Out_Additional_time.xlsx", sheet = "DATA")
atfm <- readxl::read_excel("./data-test/Airport_Arrival_ATFM_Delay.xlsx", sheet = "DATA")
```


```{r}
prepare_front_page_DT <- function(.tfc, .asma, .txot, .atfm){
  library(tidyverse)
library(DT)
library(formattable)
library(sparkline)

  tfc  <- .tfc
  asma <- .asma
  txot <- .txot
  atfm <- .atfm
  
# utility function to extract last 12 month for overview table
extract_last_months <- function(
   df
  ,n_months = 24
  ,now_year = lubridate::year( Sys.Date()) 
  ,now_month= lubridate::month(Sys.Date()) -2
  ){
  df <- df %>% 
    filter(MOF <= paste0(now_year, "-", now_month)) %>% 
    arrange(desc(MOF)) %>%
  ## force 2019 ... not sure why pip not yet updated
    filter(YEAR %in% c(2019,2018)) %>%
    head(n_months)
  if(!is.integer(df$YEAR))     {df$YEAR      <- as.integer(df$YEAR)}
  if(!is.integer(df$MONTH_NUM)){df$MONTH_NUM <- as.integer(df$MONTH_NUM)}
  return(df)
}

tfc2 <- tfc %>% filter(APT_ICAO == "EGLL") %>%
  select(YEAR, MONTH_NUM, FLT_DEP_IFR_2, FLT_ARR_IFR_2, FLT_TOT_IFR_2) %>% 
  group_by(YEAR, MONTH_NUM) %>% 
  summarise(FLT_TOT = sum(FLT_TOT_IFR_2, na.rm = TRUE)) %>% 
  mutate(MOF = paste0(YEAR,"-", sprintf("%02s", MONTH_NUM) )) %>%
  extract_last_months()
  
asma2<- asma %>% filter(APT_ICAO == "EGLL") %>% 
  select(YEAR, MONTH_NUM, ADD_ASMA = TIME_ASMA_ADD_2, N_ASMA = FLT_ASMA_UNIMP_2) %>%
  mutate( MOF = paste0(YEAR,"-", sprintf("%02d", MONTH_NUM)) ) %>%
  extract_last_months()

txot2<- txot %>% filter(APT_ICAO == "EGLL") %>%
  select(YEAR, MONTH_NUM, ADD_TXOT = TIME_TXO_ADD_2, N_TXOT = FLT_TXO_UNIMP_2) %>%
  mutate( MOF = paste0(YEAR,"-", sprintf("%02d", MONTH_NUM)) ) %>%
  extract_last_months()

atfm2<- atfm %>% filter(APT_ICAO == "EGLL") %>%
  select(YEAR, MONTH_NUM, ATFM_ADLY = DLY_APT_ARR_1, N_ATFM_A = FLT_ARR_1) %>%
  group_by(YEAR, MONTH_NUM) %>%
  summarise(ATFM_ADLY = sum(ATFM_ADLY, na.rm = TRUE), N_ATFM_A = sum(N_ATFM_A, na.rm = TRUE)) %>%
  mutate( MOF = paste0(YEAR,"-", sprintf("%02d", MONTH_NUM)) ) %>%
  extract_last_months()

#message(paste0("Results for "
#               , now_month =lubridate::month(Sys.Date()) -2, "-"
#               , now_year  =lubridate::year( Sys.Date())
#               )
#        )

perf <- tfc2 %>% 
  left_join(asma2, by=c("MOF","YEAR","MONTH_NUM")) %>% 
  left_join(txot2, by=c("MOF","YEAR","MONTH_NUM")) %>%
  left_join(atfm2, by=c("MOF","YEAR","MONTH_NUM")) %>%
  ungroup

calc_current_month <- function(.perf){
  df <- .perf %>% 
    mutate(
      DIFF_FLT      = FLT_TOT - lead(FLT_TOT)
      ,DIFF_FLT_P   = DIFF_FLT / lead(FLT_TOT)
      ,AVG_ADD_ASMA = ADD_ASMA / N_ASMA
      ,DIFF_ASMA    = AVG_ADD_ASMA - lead(AVG_ADD_ASMA)
      ,DIFF_ASMA_P  = DIFF_ASMA / lead(AVG_ADD_ASMA)
      ,AVG_ADD_TXOT = ADD_TXOT / N_TXOT
      ,DIFF_TXOT    = AVG_ADD_TXOT - lead(AVG_ADD_TXOT)
      ,DIFF_TXOT_P  = DIFF_TXOT / lead(AVG_ADD_TXOT)
      ,AVG_ATFM_ADLY= ATFM_ADLY / N_ATFM_A
      ,DIFF_ATFM_A  = AVG_ATFM_ADLY - lead(AVG_ATFM_ADLY)
      ,DIFF_ATFM_A_P= DIFF_ATFM_A / lead(AVG_ATFM_ADLY)
      ) %>%
    select(YEAR, MONTH_NUM, MOF
           , FLT_TOT, DIFF_FLT, DIFF_FLT_P
           , AVG_ADD_ASMA, DIFF_ASMA , DIFF_ASMA_P
           , AVG_ADD_TXOT, DIFF_TXOT , DIFF_TXOT_P
           , AVG_ATFM_ADLY,DIFF_ATFM_A,DIFF_ATFM_A_P
           ) %>%
    mutate_if(is.double, round, 3)     # round all doubles to n digits
  
  df$CHECK <- NA
  df$CHECK[1] <- "NOW"
  df$CHECK[13]<- "AGO"
  return(df)
}

perf2 <- perf %>% calc_current_month()

# extract sparklines, reverse order, i.e. rev(), to have timeline correct
tfc_spk   <- sparkline::spk_chr(rev(perf2$FLT_TOT[1:13]))
asma_spk  <- sparkline::spk_chr(rev(perf2$AVG_ADD_ASMA[1:13]), type="bar")
txot_spk  <- sparkline::spk_chr(rev(perf2$AVG_ADD_TXOT[1:13]), type="bar")
atfm_spk  <- sparkline::spk_chr(rev(perf2$AVG_ATFM_ADLY[1:13]), type="line")

spark_tbl <- tibble(
   IND = c("TFC"  ,"ASMA"   ,"TXOT"   ,"ATFM_A")
  ,SPK = c(tfc_spk, asma_spk, txot_spk, atfm_spk)
)

r_tfc <- perf2 %>% filter(CHECK == "NOW") %>% mutate(IND = "TFC") %>%
  select(IND, CURRENT = FLT_TOT, CHANGE_M2M_P = DIFF_FLT_P)

r_asma<- perf2 %>% filter(CHECK == "NOW") %>% mutate(IND = "ASMA") %>%
  select(IND, CURRENT = AVG_ADD_ASMA, CHANGE_M2M_P = DIFF_ASMA_P)

r_txot<- perf2 %>% filter(CHECK == "NOW") %>% mutate(IND = "TXOT") %>%
  select(IND, CURRENT = AVG_ADD_TXOT, CHANGE_M2M_P = DIFF_TXOT_P)

r_atfm<- perf2 %>% filter(CHECK == "NOW") %>% mutate(IND = "ATFM_A") %>%
  select(IND, CURRENT = AVG_ATFM_ADLY, CHANGE_M2M_P = DIFF_ATFM_A_P)

IND <- c("TFC", "ASMA","TXOT","ATFM_A")
NAM <- c("Monthly traffic", "Average additional ASMA time [min/arr]"
         ,"Average additional taxi-out time [min/dep]"
         ,"Average arrival ATFM delay [min/arr]"
         )
nam <- tibble(IND = IND, NAM = NAM)

out <- bind_rows(r_tfc, r_asma, r_txot, r_atfm)
out <- out %>% left_join(spark_tbl, by="IND")
out <- out %>% left_join(nam, by="IND")
out <- out %>% select(NAM, CURRENT, CHANGE_M2M_P, SPK)

return(out)
}
```


pump into datatable

```{r}
out <- prepare_front_page_DT(tfc, asma, txot, atfm)
out %>% 
  datatable(
      options = list(
        dom             = "t"        # show only table
        ,pageLength     = nrow(out)  # number of rows shown
        ,columnDefs     = list(list(className = 'dt-center'
                                    , targets = "_all" ))  # or targets = 0:4
          # widget callback for sparkline
          ,fnDrawCallback = htmlwidgets::JS('function(){
                                  HTMLWidgets.staticRender();  }' )
          ) #end options
      ,escape = FALSE      # set escape to FALSE for htmlwidget/sparkline
      ,colnames   = c("Indicator","Reporting Month", "% Change <br>Previous Month"
                      ,"12-month Trend")
      ) %>% 
  spk_add_deps() %>%       # add sparkline dependencies
  formatPercentage(
    3, 2    # format 3rd column as % and 2 digits
    )
```


```{r}
# https://stackoverflow.com/questions/43251214/composited-sparkline-in-r-with-dt-and-shiny
dfO <- data.frame(Type = c("A", "B", "C"),
                   Value_1 = c("1,1,2,2", "2,2,3,3", "3,3,4,4"), 
                   Value_2 = c("0,1,2,3", "2,3,4,5", "4,5,6,7"))
library(tidyr)
library(dplyr)
library(sparkline)
library(DT)

df <- dfO %>% 
    separate_rows(Value_1, Value_2) %>% 
    mutate_at(vars(starts_with('Value')) ,funs(as.integer))


df %>% 
    group_by(Type) %>% 
    summarize(l1 = spk_chr(Value_1,
                           lineColor = 'black', 
                           fillColor = '#ccc',
                           chartRangeMin = 0,
                           chartRangeMax = 8,
                           width = 80,
                           height = 60,
                           highlightLineColor = 'orange', 
                           highlightSpotColor = 'orange'),
              l2 = spk_chr(Value_2,
                           lineColor = 'black', 
                           fillColor = '#ccc',
                           chartRangeMin = 0,
                           chartRangeMax = 8,
                           width = 80,
                           height = 60,
                           highlightLineColor = 'orange', 
                           highlightSpotColor = 'orange')) %>% 
    datatable(escape = F,
              rownames = F,
              options = list(fnDrawCallback = htmlwidgets::JS('function(){
                                                              HTMLWidgets.staticRender();
                                                              }'))
    ) %>% 
    spk_add_deps()
```


